services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  nginx:
    image: nginx:1.17.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - habeets
      - habeets-back
  habeets:
    build:
      context: .
      dockerfile: Dockerfile
      target: angular-final
  habeets-back:
    build:
      context: .
      dockerfile: Dockerfile
      target: nestjs-final
    environment:
      - NODE_ENV=production
volumes:
  postgres:
