version: "3"
services:
  postgres:
    image: postgres:15.4
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      - "POSTGRES_DB=${POSTGRES_NAME}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    
  habeets-back:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: nestjs-final
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - "DATABASE_URL=${DATABASE_URL}"

  habeets:
      build:
        context: .
        dockerfile: Dockerfile
        target: angular-final
      ports:
        - "4200:80"

  nginx:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - habeets
      - habeets-back

volumes:
  postgres:
