version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  habeets:
    build:
      context: .
      dockerfile: Dockerfile
      target: angular-final
    ports:
      - '4200:4200'

  habeets-back:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: nestjs-final
    ports:
      - '3000:3000'
    environment:
      - 'DATABASE_URL=${DATABASE_URL}'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /nginx.conf
volumes:
  postgres:
