services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    enviroment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - '5432:5432'
volumes:
  postgres: